// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class StudyGroupObject : RISObject
	{
		override public string GetTableName()
		{
			return "tStudyGroups";
		}
		override public bool HasAccessColumns()
		{
			return true;
		}
		PrimaryKeyField m_StudyGroupId = new PrimaryKeyField("StudyGroupId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_StudyGroupId;
		}
		public PrimaryKeyField StudyGroupId
		{
			get
			{
				return this.m_StudyGroupId;
			}
			set
			{
				this.m_StudyGroupId = value;
			}
		}
		IntField m_StudyId = new IntField("StudyId",null);
		public IntField StudyId
		{
			get
			{
				return this.m_StudyId;
			}
			set
			{
				this.m_StudyId = value;
			}
		}
		IntField m_GroupId = new IntField("GroupId",null);
		public IntField GroupId
		{
			get
			{
				return this.m_GroupId;
			}
			set
			{
				this.m_GroupId = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[2];
			fields[0] = m_StudyId;
			fields[1] = m_GroupId;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[3];
			fields[0] = m_StudyGroupId;
			fields[1] = m_StudyId;
			fields[2] = m_GroupId;
			return fields;
		}
	}
}
