// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class StudyStatusTypeObject : RISObject
	{
		override public string GetTableName()
		{
			return "StudyStatusTypes";
		}
		override public bool HasAccessColumns()
		{
			return true;
		}
		PrimaryKeyField m_StudyStatusTypeId = new PrimaryKeyField("StudyStatusTypeId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_StudyStatusTypeId;
		}
		public PrimaryKeyField StudyStatusTypeId
		{
			get
			{
				return this.m_StudyStatusTypeId;
			}
			set
			{
				this.m_StudyStatusTypeId = value;
			}
		}
		TextField m_Status = new TextField("Status",null);
		public TextField Status
		{
			get
			{
				return this.m_Status;
			}
			set
			{
				this.m_Status = value;
			}
		}
		IntField m_ColumnOrder = new IntField("ColumnOrder",null);
		public IntField ColumnOrder
		{
			get
			{
				return this.m_ColumnOrder;
			}
			set
			{
				this.m_ColumnOrder = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[2];
			fields[0] = m_Status;
			fields[1] = m_ColumnOrder;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[3];
			fields[0] = m_StudyStatusTypeId;
			fields[1] = m_Status;
			fields[2] = m_ColumnOrder;
			return fields;
		}
	}
}
