// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class StudyDetailObject : RISObject
	{
		override public string GetTableName()
		{
			return "tStudyDetails";
		}
		override public bool HasAccessColumns()
		{
			return true;
		}
		PrimaryKeyField m_StudyDetailId = new PrimaryKeyField("StudyDetailId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_StudyDetailId;
		}
		public PrimaryKeyField StudyDetailId
		{
			get
			{
				return this.m_StudyDetailId;
			}
			set
			{
				this.m_StudyDetailId = value;
			}
		}
		IntField m_StudyId = new IntField("StudyId",null);
		public IntField StudyId
		{
			get
			{
				return this.m_StudyId;
			}
			set
			{
				this.m_StudyId = value;
			}
		}
		TextField m_TechComments = new TextField("TechComments",null);
		public TextField TechComments
		{
			get
			{
				return this.m_TechComments;
			}
			set
			{
				this.m_TechComments = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[2];
			fields[0] = m_StudyId;
			fields[1] = m_TechComments;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[3];
			fields[0] = m_StudyDetailId;
			fields[1] = m_StudyId;
			fields[2] = m_TechComments;
			return fields;
		}
	}
}
