// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class UserHospitalObject : RISObject
	{
		override public string GetTableName()
		{
			return "UserHospitals";
		}
		override public bool HasAccessColumns()
		{
			return false;
		}
		PrimaryKeyField m_UserHospitalId = new PrimaryKeyField("UserHospitalId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_UserHospitalId;
		}
		public PrimaryKeyField UserHospitalId
		{
			get
			{
				return this.m_UserHospitalId;
			}
			set
			{
				this.m_UserHospitalId = value;
			}
		}
		IntField m_UserId = new IntField("UserId",null);
		public IntField UserId
		{
			get
			{
				return this.m_UserId;
			}
			set
			{
				this.m_UserId = value;
			}
		}
		IntField m_HospitalId = new IntField("HospitalId",null);
		public IntField HospitalId
		{
			get
			{
				return this.m_HospitalId;
			}
			set
			{
				this.m_HospitalId = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[2];
			fields[0] = m_UserId;
			fields[1] = m_HospitalId;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[3];
			fields[0] = m_UserHospitalId;
			fields[1] = m_UserId;
			fields[2] = m_HospitalId;
			return fields;
		}
	}
}
