// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class ModalityDetailObject : RISObject
	{
		override public string GetTableName()
		{
			return "tModalityDetails";
		}
		override public bool HasAccessColumns()
		{
			return true;
		}
		PrimaryKeyField m_ModalityDetailId = new PrimaryKeyField("ModalityDetailId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_ModalityDetailId;
		}
		public PrimaryKeyField ModalityDetailId
		{
			get
			{
				return this.m_ModalityDetailId;
			}
			set
			{
				this.m_ModalityDetailId = value;
			}
		}
		IntField m_ModalityId = new IntField("ModalityId",null);
		public IntField ModalityId
		{
			get
			{
				return this.m_ModalityId;
			}
			set
			{
				this.m_ModalityId = value;
			}
		}
		TextField m_Manufacturer = new TextField("Manufacturer",null);
		public TextField Manufacturer
		{
			get
			{
				return this.m_Manufacturer;
			}
			set
			{
				this.m_Manufacturer = value;
			}
		}
		TextField m_ModelName = new TextField("ModelName",null);
		public TextField ModelName
		{
			get
			{
				return this.m_ModelName;
			}
			set
			{
				this.m_ModelName = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[3];
			fields[0] = m_ModalityId;
			fields[1] = m_Manufacturer;
			fields[2] = m_ModelName;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[4];
			fields[0] = m_ModalityDetailId;
			fields[1] = m_ModalityId;
			fields[2] = m_Manufacturer;
			fields[3] = m_ModelName;
			return fields;
		}
	}
}
