// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class RoleObject : RISObject
	{
		override public string GetTableName()
		{
			return "tRoles";
		}
		override public bool HasAccessColumns()
		{
			return true;
		}
		PrimaryKeyField m_RoleId = new PrimaryKeyField("RoleId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_RoleId;
		}
		public PrimaryKeyField RoleId
		{
			get
			{
				return this.m_RoleId;
			}
			set
			{
				this.m_RoleId = value;
			}
		}
		TextField m_Name = new TextField("Name",null);
		public TextField Name
		{
			get
			{
				return this.m_Name;
			}
			set
			{
				this.m_Name = value;
			}
		}
		TextField m_Description = new TextField("Description",null);
		public TextField Description
		{
			get
			{
				return this.m_Description;
			}
			set
			{
				this.m_Description = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[2];
			fields[0] = m_Name;
			fields[1] = m_Description;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[3];
			fields[0] = m_RoleId;
			fields[1] = m_Name;
			fields[2] = m_Description;
			return fields;
		}
	}
}
