// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class TempObject : RISObject
	{
		override public string GetTableName()
		{
			return "tTemps";
		}
		override public bool HasAccessColumns()
		{
			return true;
		}
		PrimaryKeyField m_TempId = new PrimaryKeyField("TempId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_TempId;
		}
		public PrimaryKeyField TempId
		{
			get
			{
				return this.m_TempId;
			}
			set
			{
				this.m_TempId = value;
			}
		}
		TextField m_Col1 = new TextField("Col1",null);
		public TextField Col1
		{
			get
			{
				return this.m_Col1;
			}
			set
			{
				this.m_Col1 = value;
			}
		}
		TextField m_Col2 = new TextField("Col2",null);
		public TextField Col2
		{
			get
			{
				return this.m_Col2;
			}
			set
			{
				this.m_Col2 = value;
			}
		}
		TextField m_Col3 = new TextField("Col3",null);
		public TextField Col3
		{
			get
			{
				return this.m_Col3;
			}
			set
			{
				this.m_Col3 = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[3];
			fields[0] = m_Col1;
			fields[1] = m_Col2;
			fields[2] = m_Col3;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[4];
			fields[0] = m_TempId;
			fields[1] = m_Col1;
			fields[2] = m_Col2;
			fields[3] = m_Col3;
			return fields;
		}
	}
}
