// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class UserObject : RISObject
	{
		override public string GetTableName()
		{
			return "tUsers";
		}
		override public bool HasAccessColumns()
		{
			return true;
		}
		PrimaryKeyField m_UserId = new PrimaryKeyField("UserId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_UserId;
		}
		public PrimaryKeyField UserId
		{
			get
			{
				return this.m_UserId;
			}
			set
			{
				this.m_UserId = value;
			}
		}
		TextField m_LoginName = new TextField("LoginName",null);
		public TextField LoginName
		{
			get
			{
				return this.m_LoginName;
			}
			set
			{
				this.m_LoginName = value;
			}
		}
		TextField m_Password = new TextField("Password",null);
		public TextField Password
		{
			get
			{
				return this.m_Password;
			}
			set
			{
				this.m_Password = value;
			}
		}
		TextField m_Name = new TextField("Name",null);
		public TextField Name
		{
			get
			{
				return this.m_Name;
			}
			set
			{
				this.m_Name = value;
			}
		}
		TextField m_IsActive = new TextField("IsActive",null);
		public TextField IsActive
		{
			get
			{
				return this.m_IsActive;
			}
			set
			{
				this.m_IsActive = value;
			}
		}
		DateTimeField m_LastLoginDate = new DateTimeField("LastLoginDate",null);
		public DateTimeField LastLoginDate
		{
			get
			{
				return this.m_LastLoginDate;
			}
			set
			{
				this.m_LastLoginDate = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[5];
			fields[0] = m_LoginName;
			fields[1] = m_Password;
			fields[2] = m_Name;
			fields[3] = m_IsActive;
			fields[4] = m_LastLoginDate;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[6];
			fields[0] = m_UserId;
			fields[1] = m_LoginName;
			fields[2] = m_Password;
			fields[3] = m_Name;
			fields[4] = m_IsActive;
			fields[5] = m_LastLoginDate;
			return fields;
		}
	}
}
