// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class FindingObject : RISObject
	{
		override public string GetTableName()
		{
			return "tFindings";
		}
		override public bool HasAccessColumns()
		{
			return true;
		}
		PrimaryKeyField m_FindingId = new PrimaryKeyField("FindingId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_FindingId;
		}
		public PrimaryKeyField FindingId
		{
			get
			{
				return this.m_FindingId;
			}
			set
			{
				this.m_FindingId = value;
			}
		}
		IntField m_StudyId = new IntField("StudyId",null);
		public IntField StudyId
		{
			get
			{
				return this.m_StudyId;
			}
			set
			{
				this.m_StudyId = value;
			}
		}
		IntField m_AudioUserId = new IntField("AudioUserId",null);
		public IntField AudioUserId
		{
			get
			{
				return this.m_AudioUserId;
			}
			set
			{
				this.m_AudioUserId = value;
			}
		}
		TextField m_AudioUserName = new TextField("AudioUserName",null);
		public TextField AudioUserName
		{
			get
			{
				return this.m_AudioUserName;
			}
			set
			{
				this.m_AudioUserName = value;
			}
		}
		TextField m_AudioReportPath = new TextField("AudioReportPath",null);
		public TextField AudioReportPath
		{
			get
			{
				return this.m_AudioReportPath;
			}
			set
			{
				this.m_AudioReportPath = value;
			}
		}
		TextField m_AudioFileName = new TextField("AudioFileName",null);
		public TextField AudioFileName
		{
			get
			{
				return this.m_AudioFileName;
			}
			set
			{
				this.m_AudioFileName = value;
			}
		}
		DateTimeField m_AudioDate = new DateTimeField("AudioDate",null);
		public DateTimeField AudioDate
		{
			get
			{
				return this.m_AudioDate;
			}
			set
			{
				this.m_AudioDate = value;
			}
		}
		TextField m_TextualTranscript = new TextField("TextualTranscript",null);
		public TextField TextualTranscript
		{
			get
			{
				return this.m_TextualTranscript;
			}
			set
			{
				this.m_TextualTranscript = value;
			}
		}
		IntField m_TranscriptUserId = new IntField("TranscriptUserId",null);
		public IntField TranscriptUserId
		{
			get
			{
				return this.m_TranscriptUserId;
			}
			set
			{
				this.m_TranscriptUserId = value;
			}
		}
		DateTimeField m_TranscriptionDate = new DateTimeField("TranscriptionDate",null);
		public DateTimeField TranscriptionDate
		{
			get
			{
				return this.m_TranscriptionDate;
			}
			set
			{
				this.m_TranscriptionDate = value;
			}
		}
		BlobField m_AudioData = new BlobField("AudioData",null);
		public BlobField AudioData
		{
			get
			{
				return this.m_AudioData;
			}
			set
			{
				this.m_AudioData = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[10];
			fields[0] = m_StudyId;
			fields[1] = m_AudioUserId;
			fields[2] = m_AudioUserName;
			fields[3] = m_AudioReportPath;
			fields[4] = m_AudioFileName;
			fields[5] = m_AudioDate;
			fields[6] = m_TextualTranscript;
			fields[7] = m_TranscriptUserId;
			fields[8] = m_TranscriptionDate;
			fields[9] = m_AudioData;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[11];
			fields[0] = m_FindingId;
			fields[1] = m_StudyId;
			fields[2] = m_AudioUserId;
			fields[3] = m_AudioUserName;
			fields[4] = m_AudioReportPath;
			fields[5] = m_AudioFileName;
			fields[6] = m_AudioDate;
			fields[7] = m_TextualTranscript;
			fields[8] = m_TranscriptUserId;
			fields[9] = m_TranscriptionDate;
			fields[10] = m_AudioData;
			return fields;
		}
	}
}
