// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class GroupObject : RISObject
	{
		override public string GetTableName()
		{
			return "tGroups";
		}
		override public bool HasAccessColumns()
		{
			return true;
		}
		PrimaryKeyField m_GroupId = new PrimaryKeyField("GroupId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_GroupId;
		}
		public PrimaryKeyField GroupId
		{
			get
			{
				return this.m_GroupId;
			}
			set
			{
				this.m_GroupId = value;
			}
		}
		TextField m_Name = new TextField("Name",null);
		public TextField Name
		{
			get
			{
				return this.m_Name;
			}
			set
			{
				this.m_Name = value;
			}
		}
		TextField m_IsDefault = new TextField("IsDefault",null);
		public TextField IsDefault
		{
			get
			{
				return this.m_IsDefault;
			}
			set
			{
				this.m_IsDefault = value;
			}
		}
		TextField m_Description = new TextField("Description",null);
		public TextField Description
		{
			get
			{
				return this.m_Description;
			}
			set
			{
				this.m_Description = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[3];
			fields[0] = m_Name;
			fields[1] = m_IsDefault;
			fields[2] = m_Description;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[4];
			fields[0] = m_GroupId;
			fields[1] = m_Name;
			fields[2] = m_IsDefault;
			fields[3] = m_Description;
			return fields;
		}
	}
}
