// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class ProcedureObject : RISObject
	{
		override public string GetTableName()
		{
			return "tProcedures";
		}
		override public bool HasAccessColumns()
		{
			return true;
		}
		PrimaryKeyField m_ProcedureId = new PrimaryKeyField("ProcedureId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_ProcedureId;
		}
		public PrimaryKeyField ProcedureId
		{
			get
			{
				return this.m_ProcedureId;
			}
			set
			{
				this.m_ProcedureId = value;
			}
		}
		IntField m_ModalityId = new IntField("ModalityId",null);
		public IntField ModalityId
		{
			get
			{
				return this.m_ModalityId;
			}
			set
			{
				this.m_ModalityId = value;
			}
		}
		TextField m_Name = new TextField("Name",null);
		public TextField Name
		{
			get
			{
				return this.m_Name;
			}
			set
			{
				this.m_Name = value;
			}
		}
		TextField m_CPTCode = new TextField("CPTCode",null);
		public TextField CPTCode
		{
			get
			{
				return this.m_CPTCode;
			}
			set
			{
				this.m_CPTCode = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[3];
			fields[0] = m_ModalityId;
			fields[1] = m_Name;
			fields[2] = m_CPTCode;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[4];
			fields[0] = m_ProcedureId;
			fields[1] = m_ModalityId;
			fields[2] = m_Name;
			fields[3] = m_CPTCode;
			return fields;
		}
	}
}
