// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class PatientObject : RISObject
	{
		override public string GetTableName()
		{
			return "tPatients";
		}
		override public bool HasAccessColumns()
		{
			return true;
		}
		PrimaryKeyField m_PatientId = new PrimaryKeyField("PatientId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_PatientId;
		}
		public PrimaryKeyField PatientId
		{
			get
			{
				return this.m_PatientId;
			}
			set
			{
				this.m_PatientId = value;
			}
		}
		TextField m_ExternalPatientId = new TextField("ExternalPatientId",null);
		public TextField ExternalPatientId
		{
			get
			{
				return this.m_ExternalPatientId;
			}
			set
			{
				this.m_ExternalPatientId = value;
			}
		}
		TextField m_Name = new TextField("Name",null);
		public TextField Name
		{
			get
			{
				return this.m_Name;
			}
			set
			{
				this.m_Name = value;
			}
		}
		DateTimeField m_DateOfBirth = new DateTimeField("DateOfBirth",null);
		public DateTimeField DateOfBirth
		{
			get
			{
				return this.m_DateOfBirth;
			}
			set
			{
				this.m_DateOfBirth = value;
			}
		}
		TextField m_Gender = new TextField("Gender",null);
		public TextField Gender
		{
			get
			{
				return this.m_Gender;
			}
			set
			{
				this.m_Gender = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[4];
			fields[0] = m_ExternalPatientId;
			fields[1] = m_Name;
			fields[2] = m_DateOfBirth;
			fields[3] = m_Gender;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[5];
			fields[0] = m_PatientId;
			fields[1] = m_ExternalPatientId;
			fields[2] = m_Name;
			fields[3] = m_DateOfBirth;
			fields[4] = m_Gender;
			return fields;
		}
	}
}
