// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class ScreenObject : RISObject
	{
		override public string GetTableName()
		{
			return "tScreens";
		}
		override public bool HasAccessColumns()
		{
			return true;
		}
		PrimaryKeyField m_ScreenId = new PrimaryKeyField("ScreenId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_ScreenId;
		}
		public PrimaryKeyField ScreenId
		{
			get
			{
				return this.m_ScreenId;
			}
			set
			{
				this.m_ScreenId = value;
			}
		}
		TextField m_Name = new TextField("Name",null);
		public TextField Name
		{
			get
			{
				return this.m_Name;
			}
			set
			{
				this.m_Name = value;
			}
		}
		TextField m_Path = new TextField("Path",null);
		public TextField Path
		{
			get
			{
				return this.m_Path;
			}
			set
			{
				this.m_Path = value;
			}
		}
		TextField m_IsActive = new TextField("IsActive",null);
		public TextField IsActive
		{
			get
			{
				return this.m_IsActive;
			}
			set
			{
				this.m_IsActive = value;
			}
		}
		TextField m_GroupName = new TextField("GroupName",null);
		public TextField GroupName
		{
			get
			{
				return this.m_GroupName;
			}
			set
			{
				this.m_GroupName = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[4];
			fields[0] = m_Name;
			fields[1] = m_Path;
			fields[2] = m_IsActive;
			fields[3] = m_GroupName;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[5];
			fields[0] = m_ScreenId;
			fields[1] = m_Name;
			fields[2] = m_Path;
			fields[3] = m_IsActive;
			fields[4] = m_GroupName;
			return fields;
		}
	}
}
