// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.DICOM
{
	public class DICOMPatientObject : DICOMObject
	{
		override public string GetTableName()
		{
			return "DICOMPatients";
		}
		override public bool HasAccessColumns()
		{
			return false;
		}
		PrimaryKeyField m_PatientID = new PrimaryKeyField("PatientID",null,false);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_PatientID;
		}
		public PrimaryKeyField PatientID
		{
			get
			{
				return this.m_PatientID;
			}
			set
			{
				this.m_PatientID = value;
			}
		}
		TextField m_Name = new TextField("PatientNam",null);
		public TextField Name
		{
			get
			{
				return this.m_Name;
			}
			set
			{
				this.m_Name = value;
			}
		}
		TextField m_DateOfBirth = new TextField("PatientBir",null);
		public TextField DateOfBirth
		{
			get
			{
				return this.m_DateOfBirth;
			}
			set
			{
				this.m_DateOfBirth = value;
			}
		}
		TextField m_Gender = new TextField("PatientSex",null);
		public TextField Gender
		{
			get
			{
				return this.m_Gender;
			}
			set
			{
				this.m_Gender = value;
			}
		}
		DateTimeField m_SyncTime = new DateTimeField("SyncTime",null);
		public DateTimeField SyncTime
		{
			get
			{
				return this.m_SyncTime;
			}
			set
			{
				this.m_SyncTime = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[4];
			fields[0] = m_Name;
			fields[1] = m_DateOfBirth;
			fields[2] = m_Gender;
			fields[3] = m_SyncTime;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[5];
			fields[0] = m_PatientID;
			fields[1] = m_Name;
			fields[2] = m_DateOfBirth;
			fields[3] = m_Gender;
			fields[4] = m_SyncTime;
			return fields;
		}
	}
}
