// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.DICOM
{
	public class DICOMWorklistObject : DICOMObject
	{
		override public string GetTableName()
		{
			return "DICOMWorkList";
		}
		override public bool HasAccessColumns()
		{
			return false;
		}
		PrimaryKeyField m_AccessionN = new PrimaryKeyField("AccessionN",null,false);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_AccessionN;
		}
		public PrimaryKeyField AccessionN
		{
			get
			{
				return this.m_AccessionN;
			}
			set
			{
				this.m_AccessionN = value;
			}
		}
		TextField m_PatientId = new TextField("PatientId",null);
		public TextField PatientId
		{
			get
			{
				return this.m_PatientId;
			}
			set
			{
				this.m_PatientId = value;
			}
		}
		TextField m_PatientName = new TextField("PatientNam",null);
		public TextField PatientName
		{
			get
			{
				return this.m_PatientName;
			}
			set
			{
				this.m_PatientName = value;
			}
		}
		TextField m_PatientBir = new TextField("PatientBir",null);
		public TextField PatientBir
		{
			get
			{
				return this.m_PatientBir;
			}
			set
			{
				this.m_PatientBir = value;
			}
		}
		TextField m_PatientSex = new TextField("PatientSex",null);
		public TextField PatientSex
		{
			get
			{
				return this.m_PatientSex;
			}
			set
			{
				this.m_PatientSex = value;
			}
		}
		TextField m_MedicalAle = new TextField("MedicalAle",null);
		public TextField MedicalAle
		{
			get
			{
				return this.m_MedicalAle;
			}
			set
			{
				this.m_MedicalAle = value;
			}
		}
		TextField m_ContrastAl = new TextField("ContrastAl",null);
		public TextField ContrastAl
		{
			get
			{
				return this.m_ContrastAl;
			}
			set
			{
				this.m_ContrastAl = value;
			}
		}
		TextField m_StudyInsta = new TextField("StudyInsta",null);
		public TextField StudyInsta
		{
			get
			{
				return this.m_StudyInsta;
			}
			set
			{
				this.m_StudyInsta = value;
			}
		}
		TextField m_ReqPhysici = new TextField("ReqPhysici",null);
		public TextField ReqPhysici
		{
			get
			{
				return this.m_ReqPhysici;
			}
			set
			{
				this.m_ReqPhysici = value;
			}
		}
		TextField m_ReqProcDes = new TextField("ReqProcDes",null);
		public TextField ReqProcDes
		{
			get
			{
				return this.m_ReqProcDes;
			}
			set
			{
				this.m_ReqProcDes = value;
			}
		}
		TextField m_Modality = new TextField("Modality",null);
		public TextField Modality
		{
			get
			{
				return this.m_Modality;
			}
			set
			{
				this.m_Modality = value;
			}
		}
		TextField m_ReqContras = new TextField("ReqContras",null);
		public TextField ReqContras
		{
			get
			{
				return this.m_ReqContras;
			}
			set
			{
				this.m_ReqContras = value;
			}
		}
		TextField m_ScheduledA = new TextField("ScheduledA",null);
		public TextField ScheduledA
		{
			get
			{
				return this.m_ScheduledA;
			}
			set
			{
				this.m_ScheduledA = value;
			}
		}
		TextField m_StartDate = new TextField("StartDate",null);
		public TextField StartDate
		{
			get
			{
				return this.m_StartDate;
			}
			set
			{
				this.m_StartDate = value;
			}
		}
		TextField m_StartTime = new TextField("StartTime",null);
		public TextField StartTime
		{
			get
			{
				return this.m_StartTime;
			}
			set
			{
				this.m_StartTime = value;
			}
		}
		TextField m_PerfPhysic = new TextField("PerfPhysic",null);
		public TextField PerfPhysic
		{
			get
			{
				return this.m_PerfPhysic;
			}
			set
			{
				this.m_PerfPhysic = value;
			}
		}
		TextField m_SchedPSDes = new TextField("SchedPSDes",null);
		public TextField SchedPSDes
		{
			get
			{
				return this.m_SchedPSDes;
			}
			set
			{
				this.m_SchedPSDes = value;
			}
		}
		TextField m_SchedPSID = new TextField("SchedPSID",null);
		public TextField SchedPSID
		{
			get
			{
				return this.m_SchedPSID;
			}
			set
			{
				this.m_SchedPSID = value;
			}
		}
		TextField m_SchedStati = new TextField("SchedStati",null);
		public TextField SchedStati
		{
			get
			{
				return this.m_SchedStati;
			}
			set
			{
				this.m_SchedStati = value;
			}
		}
		TextField m_SchedPSLoc = new TextField("SchedPSLoc",null);
		public TextField SchedPSLoc
		{
			get
			{
				return this.m_SchedPSLoc;
			}
			set
			{
				this.m_SchedPSLoc = value;
			}
		}
		TextField m_PreMedicat = new TextField("PreMedicat",null);
		public TextField PreMedicat
		{
			get
			{
				return this.m_PreMedicat;
			}
			set
			{
				this.m_PreMedicat = value;
			}
		}
		TextField m_SchedPSCom = new TextField("SchedPSCom",null);
		public TextField SchedPSCom
		{
			get
			{
				return this.m_SchedPSCom;
			}
			set
			{
				this.m_SchedPSCom = value;
			}
		}
		TextField m_ReqProcID = new TextField("ReqProcID",null);
		public TextField ReqProcID
		{
			get
			{
				return this.m_ReqProcID;
			}
			set
			{
				this.m_ReqProcID = value;
			}
		}
		TextField m_ReqProcPri = new TextField("ReqProcPri",null);
		public TextField ReqProcPri
		{
			get
			{
				return this.m_ReqProcPri;
			}
			set
			{
				this.m_ReqProcPri = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[23];
			fields[0] = m_PatientId;
			fields[1] = m_PatientName;
			fields[2] = m_PatientBir;
			fields[3] = m_PatientSex;
			fields[4] = m_MedicalAle;
			fields[5] = m_ContrastAl;
			fields[6] = m_StudyInsta;
			fields[7] = m_ReqPhysici;
			fields[8] = m_ReqProcDes;
			fields[9] = m_Modality;
			fields[10] = m_ReqContras;
			fields[11] = m_ScheduledA;
			fields[12] = m_StartDate;
			fields[13] = m_StartTime;
			fields[14] = m_PerfPhysic;
			fields[15] = m_SchedPSDes;
			fields[16] = m_SchedPSID;
			fields[17] = m_SchedStati;
			fields[18] = m_SchedPSLoc;
			fields[19] = m_PreMedicat;
			fields[20] = m_SchedPSCom;
			fields[21] = m_ReqProcID;
			fields[22] = m_ReqProcPri;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[24];
			fields[0] = m_AccessionN;
			fields[1] = m_PatientId;
			fields[2] = m_PatientName;
			fields[3] = m_PatientBir;
			fields[4] = m_PatientSex;
			fields[5] = m_MedicalAle;
			fields[6] = m_ContrastAl;
			fields[7] = m_StudyInsta;
			fields[8] = m_ReqPhysici;
			fields[9] = m_ReqProcDes;
			fields[10] = m_Modality;
			fields[11] = m_ReqContras;
			fields[12] = m_ScheduledA;
			fields[13] = m_StartDate;
			fields[14] = m_StartTime;
			fields[15] = m_PerfPhysic;
			fields[16] = m_SchedPSDes;
			fields[17] = m_SchedPSID;
			fields[18] = m_SchedStati;
			fields[19] = m_SchedPSLoc;
			fields[20] = m_PreMedicat;
			fields[21] = m_SchedPSCom;
			fields[22] = m_ReqProcID;
			fields[23] = m_ReqProcPri;
			return fields;
		}
	}
}
