// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class TypeObject : RISObject
	{
		override public string GetTableName()
		{
			return "tTypes";
		}
		override public bool HasAccessColumns()
		{
			return true;
		}
		PrimaryKeyField m_TypeId = new PrimaryKeyField("TypeId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_TypeId;
		}
		public PrimaryKeyField TypeId
		{
			get
			{
				return this.m_TypeId;
			}
			set
			{
				this.m_TypeId = value;
			}
		}
		TextField m_Group = new TextField("Group",null);
		public TextField Group
		{
			get
			{
				return this.m_Group;
			}
			set
			{
				this.m_Group = value;
			}
		}
		TextField m_Value = new TextField("Value",null);
		public TextField Value
		{
			get
			{
				return this.m_Value;
			}
			set
			{
				this.m_Value = value;
			}
		}
		TextField m_Description = new TextField("Description",null);
		public TextField Description
		{
			get
			{
				return this.m_Description;
			}
			set
			{
				this.m_Description = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[3];
			fields[0] = m_Group;
			fields[1] = m_Value;
			fields[2] = m_Description;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[4];
			fields[0] = m_TypeId;
			fields[1] = m_Group;
			fields[2] = m_Value;
			fields[3] = m_Description;
			return fields;
		}
	}
}
