// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.DICOM
{
	public class DICOMMODObject : DICOMObject
	{
		override public string GetTableName()
		{
			return "UIDMODS";
		}
		override public bool HasAccessColumns()
		{
			return false;
		}
		PrimaryKeyField m_OldUID = new PrimaryKeyField("OldUID",null,false);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_OldUID;
		}
		public PrimaryKeyField OldUID
		{
			get
			{
				return this.m_OldUID;
			}
			set
			{
				this.m_OldUID = value;
			}
		}
		IntField m_MODTIme = new IntField("MODTIme",null);
		public IntField MODTIme
		{
			get
			{
				return this.m_MODTIme;
			}
			set
			{
				this.m_MODTIme = value;
			}
		}
		TextField m_NewUID = new TextField("NewUID",null);
		public TextField NewUID
		{
			get
			{
				return this.m_NewUID;
			}
			set
			{
				this.m_NewUID = value;
			}
		}
		TextField m_MODType = new TextField("MODType",null);
		public TextField MODType
		{
			get
			{
				return this.m_MODType;
			}
			set
			{
				this.m_MODType = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[3];
			fields[0] = m_MODTIme;
			fields[1] = m_NewUID;
			fields[2] = m_MODType;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[4];
			fields[0] = m_OldUID;
			fields[1] = m_MODTIme;
			fields[2] = m_NewUID;
			fields[3] = m_MODType;
			return fields;
		}
	}
}
