// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.DICOM
{
	public class DICOMImageObject : DICOMObject
	{
		override public string GetTableName()
		{
			return "DICOMImages";
		}
		override public bool HasAccessColumns()
		{
			return false;
		}
		PrimaryKeyField m_ImageInstance = new PrimaryKeyField("SOPInstanc",null,false);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_ImageInstance;
		}
		public PrimaryKeyField ImageInstance
		{
			get
			{
				return this.m_ImageInstance;
			}
			set
			{
				this.m_ImageInstance = value;
			}
		}
		IntField m_ImageClassUI = new IntField("SOPClassUI",null);
		public IntField ImageClassUI
		{
			get
			{
				return this.m_ImageClassUI;
			}
			set
			{
				this.m_ImageClassUI = value;
			}
		}
		TextField m_ImageNumber = new TextField("ImageNumbe",null);
		public TextField ImageNumber
		{
			get
			{
				return this.m_ImageNumber;
			}
			set
			{
				this.m_ImageNumber = value;
			}
		}
		TextField m_ImageDate = new TextField("ImageDate",null);
		public TextField ImageDate
		{
			get
			{
				return this.m_ImageDate;
			}
			set
			{
				this.m_ImageDate = value;
			}
		}
		IntField m_ImageTime = new IntField("ImageTime",null);
		public IntField ImageTime
		{
			get
			{
				return this.m_ImageTime;
			}
			set
			{
				this.m_ImageTime = value;
			}
		}
		IntField m_EchoNumber = new IntField("EchoNumber",null);
		public IntField EchoNumber
		{
			get
			{
				return this.m_EchoNumber;
			}
			set
			{
				this.m_EchoNumber = value;
			}
		}
		IntField m_NumberOfFrames = new IntField("NumberOfFr",null);
		public IntField NumberOfFrames
		{
			get
			{
				return this.m_NumberOfFrames;
			}
			set
			{
				this.m_NumberOfFrames = value;
			}
		}
		TextField m_AcqDate = new TextField("AcqDate",null);
		public TextField AcqDate
		{
			get
			{
				return this.m_AcqDate;
			}
			set
			{
				this.m_AcqDate = value;
			}
		}
		TextField m_AcqTime = new TextField("AcqTime",null);
		public TextField AcqTime
		{
			get
			{
				return this.m_AcqTime;
			}
			set
			{
				this.m_AcqTime = value;
			}
		}
		TextField m_ReceivingC = new TextField("ReceivingC",null);
		public TextField ReceivingC
		{
			get
			{
				return this.m_ReceivingC;
			}
			set
			{
				this.m_ReceivingC = value;
			}
		}
		TextField m_AcqNumber = new TextField("AcqNumber",null);
		public TextField AcqNumber
		{
			get
			{
				return this.m_AcqNumber;
			}
			set
			{
				this.m_AcqNumber = value;
			}
		}
		TextField m_SliceLocation = new TextField("SliceLocat",null);
		public TextField SliceLocation
		{
			get
			{
				return this.m_SliceLocation;
			}
			set
			{
				this.m_SliceLocation = value;
			}
		}
		TextField m_NumberOfSamples = new TextField("SamplesPer",null);
		public TextField NumberOfSamples
		{
			get
			{
				return this.m_NumberOfSamples;
			}
			set
			{
				this.m_NumberOfSamples = value;
			}
		}
		TextField m_PhotoMetric = new TextField("PhotoMetri",null);
		public TextField PhotoMetric
		{
			get
			{
				return this.m_PhotoMetric;
			}
			set
			{
				this.m_PhotoMetric = value;
			}
		}
		TextField m_BitsStored = new TextField("BitsStored",null);
		public TextField BitsStored
		{
			get
			{
				return this.m_BitsStored;
			}
			set
			{
				this.m_BitsStored = value;
			}
		}
		TextField m_Rows = new TextField("Rows",null);
		public TextField Rows
		{
			get
			{
				return this.m_Rows;
			}
			set
			{
				this.m_Rows = value;
			}
		}
		TextField m_Columns = new TextField("Colums",null);
		public TextField Columns
		{
			get
			{
				return this.m_Columns;
			}
			set
			{
				this.m_Columns = value;
			}
		}
		TextField m_ImageType = new TextField("ImageType",null);
		public TextField ImageType
		{
			get
			{
				return this.m_ImageType;
			}
			set
			{
				this.m_ImageType = value;
			}
		}
		TextField m_ImageID = new TextField("ImageID",null);
		public TextField ImageID
		{
			get
			{
				return this.m_ImageID;
			}
			set
			{
				this.m_ImageID = value;
			}
		}
		TextField m_ImagePat = new TextField("ImagePat",null);
		public TextField ImagePat
		{
			get
			{
				return this.m_ImagePat;
			}
			set
			{
				this.m_ImagePat = value;
			}
		}
		TextField m_SeriesInst = new TextField("SeriesInst",null);
		public TextField SeriesInst
		{
			get
			{
				return this.m_SeriesInst;
			}
			set
			{
				this.m_SeriesInst = value;
			}
		}
		TextField m_ObjectFile = new TextField("ObjectFile",null);
		public TextField ObjectFile
		{
			get
			{
				return this.m_ObjectFile;
			}
			set
			{
				this.m_ObjectFile = value;
			}
		}
		TextField m_DeviceName = new TextField("DeviceName",null);
		public TextField DeviceName
		{
			get
			{
				return this.m_DeviceName;
			}
			set
			{
				this.m_DeviceName = value;
			}
		}
		DateTimeField m_SyncTime = new DateTimeField("SyncTime",null);
		public DateTimeField SyncTime
		{
			get
			{
				return this.m_SyncTime;
			}
			set
			{
				this.m_SyncTime = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[23];
			fields[0] = m_ImageClassUI;
			fields[1] = m_ImageNumber;
			fields[2] = m_ImageDate;
			fields[3] = m_ImageTime;
			fields[4] = m_EchoNumber;
			fields[5] = m_NumberOfFrames;
			fields[6] = m_AcqDate;
			fields[7] = m_AcqTime;
			fields[8] = m_ReceivingC;
			fields[9] = m_AcqNumber;
			fields[10] = m_SliceLocation;
			fields[11] = m_NumberOfSamples;
			fields[12] = m_PhotoMetric;
			fields[13] = m_BitsStored;
			fields[14] = m_Rows;
			fields[15] = m_Columns;
			fields[16] = m_ImageType;
			fields[17] = m_ImageID;
			fields[18] = m_ImagePat;
			fields[19] = m_SeriesInst;
			fields[20] = m_ObjectFile;
			fields[21] = m_DeviceName;
			fields[22] = m_SyncTime;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[24];
			fields[0] = m_ImageInstance;
			fields[1] = m_ImageClassUI;
			fields[2] = m_ImageNumber;
			fields[3] = m_ImageDate;
			fields[4] = m_ImageTime;
			fields[5] = m_EchoNumber;
			fields[6] = m_NumberOfFrames;
			fields[7] = m_AcqDate;
			fields[8] = m_AcqTime;
			fields[9] = m_ReceivingC;
			fields[10] = m_AcqNumber;
			fields[11] = m_SliceLocation;
			fields[12] = m_NumberOfSamples;
			fields[13] = m_PhotoMetric;
			fields[14] = m_BitsStored;
			fields[15] = m_Rows;
			fields[16] = m_Columns;
			fields[17] = m_ImageType;
			fields[18] = m_ImageID;
			fields[19] = m_ImagePat;
			fields[20] = m_SeriesInst;
			fields[21] = m_ObjectFile;
			fields[22] = m_DeviceName;
			fields[23] = m_SyncTime;
			return fields;
		}
	}
}
