/**************************************************************************
-- -Generated by xSQL SDK for Schema Comparison and Synchronization
-- -Date/Time: August 11, 2010 00:05:47

-- -Summary:
    Contains the T-SQL script that makes the database 
    .\SQL2005.RIS_PROD the same as the database .\SQL2005.RIS

-- -Action:
    Execute this script on .\SQL2005.RIS_PROD

-- -SQL Server version: 9.00.4053
**************************************************************************/

BEGIN TRANSACTION
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
	SET QUOTED_IDENTIFIER ON
	SET ANSI_NULLS ON
	SET ANSI_PADDING ON
	SET ANSI_WARNINGS ON
	SET ARITHABORT ON
	SET NUMERIC_ROUNDABORT OFF
	SET CONCAT_NULL_YIELDS_NULL ON
	SET XACT_ABORT ON
COMMIT TRANSACTION
GO

IF EXISTS (select * from tempdb..sysobjects where id = OBJECT_ID('tempdb..#ErrorLog')) 
	DROP TABLE #ErrorLog 
CREATE TABLE #ErrorLog 
( pkid [int] IDENTITY(1,1) NOT NULL, errno [int] NOT NULL, errdescr [varchar](100) NULL )
GO

IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tAttachments] (
	[AttachmentId] [int] IDENTITY (1,1) NOT NULL,
	[StudyId] [int] NOT NULL,
	[Name] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Description] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ScannedBy] [int] NOT NULL,
	[ScannedTime] [datetime] NOT NULL,
	[AttachmentData] varbinary(max) NULL,
	[AttachmentType] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add table dbo.tAttachments')
END
GO

IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tCarriers] (
	[CarrierId] [int] IDENTITY (1,1) NOT NULL,
	[Name] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[EmailServer] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add table dbo.tCarriers')
END
GO

IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
ALTER TABLE [dbo].[tTemplates]
	ADD [Heading] varchar(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add column dbo.tTemplates.Heading')
END
GO
IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
ALTER TABLE [dbo].[tTemplates]
	ADD [Description] varchar(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add column dbo.tTemplates.Description')
END
GO
IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
ALTER TABLE [dbo].[tTemplates]
	ADD [Impression] varchar(max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add column dbo.tTemplates.Impression')
END
GO
IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
ALTER TABLE [dbo].[tUsers]
	ADD [Mobile] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add column dbo.tUsers.Mobile')
END
GO
IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
ALTER TABLE [dbo].[tClients]
	ADD [Website] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add column dbo.tClients.Website')
END
GO
IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
ALTER TABLE [dbo].[tUsers]
	ADD [CarrierId] [int] NULL
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add column dbo.tUsers.CarrierId')
END
GO
IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
ALTER TABLE [dbo].[tUsers]
	ADD [SendSMS] [bit] NULL
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add column dbo.tUsers.SendSMS')
END
GO
IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE dbo.AttachmentDelete
(
	@Original_AttachmentId int
)
AS
	SET NOCOUNT OFF;
DELETE FROM [tAttachments] WHERE (([AttachmentId] = @Original_AttachmentId))
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add stored procedure dbo.AttachmentDelete')
END
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE dbo.AttachmentInsert
(
	@StudyId int,
	@Name varchar(100),
	@Description varchar(500),
	@ScannedBy int,
	@ScannedTime datetime,
	@AttachmentData varbinary(MAX)
)
AS
	SET NOCOUNT OFF;
INSERT INTO [tAttachments] ([StudyId], [Name], [Description], [ScannedBy], [ScannedTime], [AttachmentData]) VALUES (@StudyId, @Name, @Description, @ScannedBy, @ScannedTime, @AttachmentData);
	
SELECT AttachmentId, StudyId, Name, Description, ScannedBy, ScannedTime, AttachmentData FROM tAttachments WHERE (AttachmentId = SCOPE_IDENTITY())
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add stored procedure dbo.AttachmentInsert')
END
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[AttachmentSelect]
@studyId int
AS
	SET NOCOUNT ON;
SELECT        tAttachments.*,tUsers.Name as UserName
FROM            tAttachments
INNER JOIN tUsers ON ScannedBy = UserId
WHERE StudyId = @studyId
order by ScannedTime DESC
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add stored procedure dbo.AttachmentSelect')
END
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[AttachmentUpdate]
(
	@Name varchar(100),
	@Description varchar(500),
	@Original_AttachmentId int,
	@AttachmentId int
)
AS
	SET NOCOUNT OFF;
UPDATE [tAttachments] SET [Name] = @Name, [Description] = @Description WHERE (([AttachmentId] = @Original_AttachmentId));
	

GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add stored procedure dbo.AttachmentUpdate')
END
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE dbo.CarrierDelete
(
	@Original_CarrierId int
)
AS
	SET NOCOUNT OFF;
DELETE FROM [tCarriers] WHERE (([CarrierId] = @Original_CarrierId))
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add stored procedure dbo.CarrierDelete')
END
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE dbo.CarrierInsert
(
	@Name varchar(100),
	@EmailServer varchar(100)
)
AS
	SET NOCOUNT OFF;
INSERT INTO [tCarriers] ([Name], [EmailServer]) VALUES (@Name, @EmailServer);
	
SELECT CarrierId, Name, EmailServer FROM tCarriers WHERE (CarrierId = SCOPE_IDENTITY())
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add stored procedure dbo.CarrierInsert')
END
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[CarrierSelect]
AS
	SET NOCOUNT ON;
SELECT        tCarriers.*
FROM            tCarriers
Order By Name
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add stored procedure dbo.CarrierSelect')
END
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE dbo.CarrierUpdate
(
	@Name varchar(100),
	@EmailServer varchar(100),
	@Original_CarrierId int,
	@CarrierId int
)
AS
	SET NOCOUNT OFF;
UPDATE [tCarriers] SET [Name] = @Name, [EmailServer] = @EmailServer WHERE (([CarrierId] = @Original_CarrierId));
	
SELECT CarrierId, Name, EmailServer FROM tCarriers WHERE (CarrierId = @CarrierId)
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add stored procedure dbo.CarrierUpdate')
END
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE dbo.TemplateDelete
(
	@Original_TemplateId int
)
AS
	SET NOCOUNT OFF;
DELETE FROM [tTemplates] WHERE (([TemplateId] = @Original_TemplateId))
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add stored procedure dbo.TemplateDelete')
END
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE dbo.TemplateInsert
(
	@ModalityId int,
	@BodyPart varchar(100),
	@Name varchar(500),
	@Text varchar(MAX),
	@Heading varchar(MAX),
	@Description varchar(MAX),
	@Impression varchar(MAX)
)
AS
	SET NOCOUNT OFF;
INSERT INTO [tTemplates] ([ModalityId], [BodyPart], [Name], [Text], [Heading], [Description], [Impression]) VALUES (@ModalityId, @BodyPart, @Name, @Text, @Heading, @Description, @Impression);
	
SELECT TemplateId, ModalityId, BodyPart, Name, Text, Heading, Description, Impression FROM tTemplates WHERE (TemplateId = SCOPE_IDENTITY())
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add stored procedure dbo.TemplateInsert')
END
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[TemplateSelect]
	@userId int
AS
	SET NOCOUNT ON;
SELECT  tTemplates.TemplateId,tTemplates.ModalityId,tModalities.Name as ModalityName,
		BodyPart,tTemplates.Name as TemplateName,[Text],Heading,[Description],Impression
  FROM  tTemplates
INNER JOIN tTemplateUsers on tTemplateUsers.TemplateId = tTemplates.TemplateId
INNER JOIN tModalities on tModalities.ModalityId = tTemplates.ModalityId
WHERE UserId = @userId
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add stored procedure dbo.TemplateSelect')
END
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[TemplateSelectById]
	@templateId int
AS
	SET NOCOUNT ON;
SELECT  tTemplates.TemplateId,tTemplates.ModalityId,tModalities.Name as ModalityName,
		BodyPart,tTemplates.Name as TemplateName,[Text],Heading,[Description],Impression
  FROM  tTemplates
INNER JOIN tModalities on tModalities.ModalityId = tTemplates.ModalityId
WHERE TemplateId = @templateId
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add stored procedure dbo.TemplateSelectById')
END
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE dbo.TemplateUpdate
(
	@ModalityId int,
	@BodyPart varchar(100),
	@Name varchar(500),
	@Text varchar(MAX),
	@Heading varchar(MAX),
	@Description varchar(MAX),
	@Impression varchar(MAX),
	@Original_TemplateId int,
	@TemplateId int
)
AS
	SET NOCOUNT OFF;
UPDATE [tTemplates] SET [ModalityId] = @ModalityId, [BodyPart] = @BodyPart, [Name] = @Name, [Text] = @Text, [Heading] = @Heading, [Description] = @Description, [Impression] = @Impression WHERE (([TemplateId] = @Original_TemplateId));
	
SELECT TemplateId, ModalityId, BodyPart, Name, Text, Heading, Description, Impression FROM tTemplates WHERE (TemplateId = @TemplateId)
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add stored procedure dbo.TemplateUpdate')
END
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[tCarriers] ADD 
	CONSTRAINT [PK_tCarriers] PRIMARY KEY CLUSTERED 
	(
		[CarrierId]
	) ON [PRIMARY];
GO

IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add primary key dbo.tCarriers.PK_tCarriers')
END
GO
IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[tAttachments] ADD 
	CONSTRAINT [PK_tAttachments] PRIMARY KEY CLUSTERED 
	(
		[AttachmentId]
	) ON [PRIMARY];
GO

IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add primary key dbo.tAttachments.PK_tAttachments')
END
GO
IF @@TRANCOUNT=0 BEGIN TRANSACTION
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER TABLE [dbo].[tUsers] ADD 
	CONSTRAINT [FK_tUsers_tCarriers] FOREIGN KEY 
	(
		[CarrierId]
	)REFERENCES [dbo].[tCarriers](
		[CarrierId]
	)ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
IF @@ERROR<>0 
Begin
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
	INSERT INTO #ErrorLog (errno,errdescr) values(@@ERROR,'Failed to add foreign key dbo.tUsers.FK_tUsers_tCarriers')
END
GO
IF EXISTS (Select * from #ErrorLog)
BEGIN
	IF @@TRANCOUNT>0 ROLLBACK TRANSACTION
END
ELSE
BEGIN
	IF @@TRANCOUNT>0 COMMIT TRANSACTION
END
IF EXISTS (Select * from #ErrorLog)
BEGIN
	Print 'Database synchronization script failed'
	GOTO QuitWithErrors
END
ELSE
BEGIN
	Print 'Database synchronization completed successfully'
END



QuitWithErrors:


