// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class AttachmentObject : RISObject
	{
		override public string GetTableName()
		{
			return "Attachments";
		}
		override public bool HasAccessColumns()
		{
			return false;
		}
		PrimaryKeyField m_AttachmentId = new PrimaryKeyField("AttachmentId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_AttachmentId;
		}
		public PrimaryKeyField AttachmentId
		{
			get
			{
				return this.m_AttachmentId;
			}
			set
			{
				this.m_AttachmentId = value;
			}
		}
		IntField m_StudyId = new IntField("StudyId",null);
		public IntField StudyId
		{
			get
			{
				return this.m_StudyId;
			}
			set
			{
				this.m_StudyId = value;
			}
		}
		TextField m_Name = new TextField("Name",null);
		public TextField Name
		{
			get
			{
				return this.m_Name;
			}
			set
			{
				this.m_Name = value;
			}
		}
		TextField m_Description = new TextField("Description",null);
		public TextField Description
		{
			get
			{
				return this.m_Description;
			}
			set
			{
				this.m_Description = value;
			}
		}
		IntField m_ScannedBy = new IntField("ScannedBy",null);
		public IntField ScannedBy
		{
			get
			{
				return this.m_ScannedBy;
			}
			set
			{
				this.m_ScannedBy = value;
			}
		}
		DateTimeField m_ScannedTime = new DateTimeField("ScannedTime",null);
		public DateTimeField ScannedTime
		{
			get
			{
				return this.m_ScannedTime;
			}
			set
			{
				this.m_ScannedTime = value;
			}
		}
		BlobField m_AttachmentData = new BlobField("AttachmentData",null);
		public BlobField AttachmentData
		{
			get
			{
				return this.m_AttachmentData;
			}
			set
			{
				this.m_AttachmentData = value;
			}
		}
		TextField m_AttachmentType = new TextField("AttachmentType",null);
		public TextField AttachmentType
		{
			get
			{
				return this.m_AttachmentType;
			}
			set
			{
				this.m_AttachmentType = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[7];
			fields[0] = m_StudyId;
			fields[1] = m_Name;
			fields[2] = m_Description;
			fields[3] = m_ScannedBy;
			fields[4] = m_ScannedTime;
			fields[5] = m_AttachmentData;
			fields[6] = m_AttachmentType;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[8];
			fields[0] = m_AttachmentId;
			fields[1] = m_StudyId;
			fields[2] = m_Name;
			fields[3] = m_Description;
			fields[4] = m_ScannedBy;
			fields[5] = m_ScannedTime;
			fields[6] = m_AttachmentData;
			fields[7] = m_AttachmentType;
			return fields;
		}
	}
}
