// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class CarrierObject : RISObject
	{
		override public string GetTableName()
		{
			return "Carriers";
		}
		override public bool HasAccessColumns()
		{
			return false;
		}
		PrimaryKeyField m_CarrierId = new PrimaryKeyField("CarrierId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_CarrierId;
		}
		public PrimaryKeyField CarrierId
		{
			get
			{
				return this.m_CarrierId;
			}
			set
			{
				this.m_CarrierId = value;
			}
		}
		TextField m_Name = new TextField("Name",null);
		public TextField Name
		{
			get
			{
				return this.m_Name;
			}
			set
			{
				this.m_Name = value;
			}
		}
		TextField m_EmailServer = new TextField("EmailServer",null);
		public TextField EmailServer
		{
			get
			{
				return this.m_EmailServer;
			}
			set
			{
				this.m_EmailServer = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[2];
			fields[0] = m_Name;
			fields[1] = m_EmailServer;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[3];
			fields[0] = m_CarrierId;
			fields[1] = m_Name;
			fields[2] = m_EmailServer;
			return fields;
		}
	}
}
