// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class RoleScreenObject : RISObject
	{
		override public string GetTableName()
		{
			return "RoleScreens";
		}
		override public bool HasAccessColumns()
		{
			return true;
		}
		PrimaryKeyField m_RoleScreenId = new PrimaryKeyField("RoleScreenId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_RoleScreenId;
		}
		public PrimaryKeyField RoleScreenId
		{
			get
			{
				return this.m_RoleScreenId;
			}
			set
			{
				this.m_RoleScreenId = value;
			}
		}
		IntField m_RoleId = new IntField("RoleId",null);
		public IntField RoleId
		{
			get
			{
				return this.m_RoleId;
			}
			set
			{
				this.m_RoleId = value;
			}
		}
		IntField m_ScreenId = new IntField("ScreenId",null);
		public IntField ScreenId
		{
			get
			{
				return this.m_ScreenId;
			}
			set
			{
				this.m_ScreenId = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[2];
			fields[0] = m_RoleId;
			fields[1] = m_ScreenId;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[3];
			fields[0] = m_RoleScreenId;
			fields[1] = m_RoleId;
			fields[2] = m_ScreenId;
			return fields;
		}
	}
}
