// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class TemplateObject : RISObject
	{
		override public string GetTableName()
		{
			return "Templates";
		}
		override public bool HasAccessColumns()
		{
			return false;
		}
		PrimaryKeyField m_TemplateId = new PrimaryKeyField("TemplateId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_TemplateId;
		}
		public PrimaryKeyField TemplateId
		{
			get
			{
				return this.m_TemplateId;
			}
			set
			{
				this.m_TemplateId = value;
			}
		}
		IntField m_ModalityId = new IntField("ModalityId",null);
		public IntField ModalityId
		{
			get
			{
				return this.m_ModalityId;
			}
			set
			{
				this.m_ModalityId = value;
			}
		}
		TextField m_BodyPart = new TextField("BodyPart",null);
		public TextField BodyPart
		{
			get
			{
				return this.m_BodyPart;
			}
			set
			{
				this.m_BodyPart = value;
			}
		}
		TextField m_Name = new TextField("Name",null);
		public TextField Name
		{
			get
			{
				return this.m_Name;
			}
			set
			{
				this.m_Name = value;
			}
		}
		TextField m_Text = new TextField("Text",null);
		public TextField Text
		{
			get
			{
				return this.m_Text;
			}
			set
			{
				this.m_Text = value;
			}
		}
		TextField m_Heading = new TextField("Heading",null);
		public TextField Heading
		{
			get
			{
				return this.m_Heading;
			}
			set
			{
				this.m_Heading = value;
			}
		}
		TextField m_Description = new TextField("Description",null);
		public TextField Description
		{
			get
			{
				return this.m_Description;
			}
			set
			{
				this.m_Description = value;
			}
		}
		TextField m_Impression = new TextField("Impression",null);
		public TextField Impression
		{
			get
			{
				return this.m_Impression;
			}
			set
			{
				this.m_Impression = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[7];
			fields[0] = m_ModalityId;
			fields[1] = m_BodyPart;
			fields[2] = m_Name;
			fields[3] = m_Text;
			fields[4] = m_Heading;
			fields[5] = m_Description;
			fields[6] = m_Impression;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[8];
			fields[0] = m_TemplateId;
			fields[1] = m_ModalityId;
			fields[2] = m_BodyPart;
			fields[3] = m_Name;
			fields[4] = m_Text;
			fields[5] = m_Heading;
			fields[6] = m_Description;
			fields[7] = m_Impression;
			return fields;
		}
	}
}
