// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class UserClientObject : RISObject
	{
		override public string GetTableName()
		{
			return "UserClients";
		}
		override public bool HasAccessColumns()
		{
			return false;
		}
		PrimaryKeyField m_UserClientId = new PrimaryKeyField("UserClientId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_UserClientId;
		}
		public PrimaryKeyField UserClientId
		{
			get
			{
				return this.m_UserClientId;
			}
			set
			{
				this.m_UserClientId = value;
			}
		}
		IntField m_ClientId = new IntField("ClientId",null);
		public IntField ClientId
		{
			get
			{
				return this.m_ClientId;
			}
			set
			{
				this.m_ClientId = value;
			}
		}
		IntField m_UserId = new IntField("UserId",null);
		public IntField UserId
		{
			get
			{
				return this.m_UserId;
			}
			set
			{
				this.m_UserId = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[2];
			fields[0] = m_ClientId;
			fields[1] = m_UserId;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[3];
			fields[0] = m_UserClientId;
			fields[1] = m_ClientId;
			fields[2] = m_UserId;
			return fields;
		}
	}
}
