// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class RoleManagementObject : RISObject
	{
		override public string GetTableName()
		{
			return "tRoleManagements";
		}
		override public bool HasAccessColumns()
		{
			return true;
		}
		PrimaryKeyField m_RoleManagementId = new PrimaryKeyField("RoleManagementId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_RoleManagementId;
		}
		public PrimaryKeyField RoleManagementId
		{
			get
			{
				return this.m_RoleManagementId;
			}
			set
			{
				this.m_RoleManagementId = value;
			}
		}
		IntField m_ManagerRoleId = new IntField("ManagerRoleId",null);
		public IntField ManagerRoleId
		{
			get
			{
				return this.m_ManagerRoleId;
			}
			set
			{
				this.m_ManagerRoleId = value;
			}
		}
		IntField m_NormalRoleId = new IntField("NormalRoleId",null);
		public IntField NormalRoleId
		{
			get
			{
				return this.m_NormalRoleId;
			}
			set
			{
				this.m_NormalRoleId = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[2];
			fields[0] = m_ManagerRoleId;
			fields[1] = m_NormalRoleId;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[3];
			fields[0] = m_RoleManagementId;
			fields[1] = m_ManagerRoleId;
			fields[2] = m_NormalRoleId;
			return fields;
		}
	}
}
