// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class TemplateUserObject : RISObject
	{
		override public string GetTableName()
		{
			return "tTemplateUsers";
		}
		override public bool HasAccessColumns()
		{
			return false;
		}
		PrimaryKeyField m_TemplateUserId = new PrimaryKeyField("TemplateUserId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_TemplateUserId;
		}
		public PrimaryKeyField TemplateUserId
		{
			get
			{
				return this.m_TemplateUserId;
			}
			set
			{
				this.m_TemplateUserId = value;
			}
		}
		IntField m_UserId = new IntField("UserId",null);
		public IntField UserId
		{
			get
			{
				return this.m_UserId;
			}
			set
			{
				this.m_UserId = value;
			}
		}
		IntField m_TemplateId = new IntField("TemplateId",null);
		public IntField TemplateId
		{
			get
			{
				return this.m_TemplateId;
			}
			set
			{
				this.m_TemplateId = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[2];
			fields[0] = m_UserId;
			fields[1] = m_TemplateId;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[3];
			fields[0] = m_TemplateUserId;
			fields[1] = m_UserId;
			fields[2] = m_TemplateId;
			return fields;
		}
	}
}
