// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class LogObject : RISObject
	{
		override public string GetTableName()
		{
			return "Logs";
		}
		override public bool HasAccessColumns()
		{
			return false;
		}
		PrimaryKeyField m_LogId = new PrimaryKeyField("LogId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_LogId;
		}
		public PrimaryKeyField LogId
		{
			get
			{
				return this.m_LogId;
			}
			set
			{
				this.m_LogId = value;
			}
		}
		IntField m_StudyId = new IntField("StudyId",null);
		public IntField StudyId
		{
			get
			{
				return this.m_StudyId;
			}
			set
			{
				this.m_StudyId = value;
			}
		}
		IntField m_PatientId = new IntField("PatientId",null);
		public IntField PatientId
		{
			get
			{
				return this.m_PatientId;
			}
			set
			{
				this.m_PatientId = value;
			}
		}
		IntField m_UserId = new IntField("UserId",null);
		public IntField UserId
		{
			get
			{
				return this.m_UserId;
			}
			set
			{
				this.m_UserId = value;
			}
		}
		TextField m_Action = new TextField("Action",null);
		public TextField Action
		{
			get
			{
				return this.m_Action;
			}
			set
			{
				this.m_Action = value;
			}
		}
		DateTimeField m_ActionTime = new DateTimeField("ActionTime",null);
		public DateTimeField ActionTime
		{
			get
			{
				return this.m_ActionTime;
			}
			set
			{
				this.m_ActionTime = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[5];
			fields[0] = m_StudyId;
			fields[1] = m_PatientId;
			fields[2] = m_UserId;
			fields[3] = m_Action;
			fields[4] = m_ActionTime;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[6];
			fields[0] = m_LogId;
			fields[1] = m_StudyId;
			fields[2] = m_PatientId;
			fields[3] = m_UserId;
			fields[4] = m_Action;
			fields[5] = m_ActionTime;
			return fields;
		}
	}
}
