// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class SeriesObject : RISObject
	{
		override public string GetTableName()
		{
			return "Series";
		}
		override public bool HasAccessColumns()
		{
			return true;
		}
		PrimaryKeyField m_SeriesId = new PrimaryKeyField("SeriesId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_SeriesId;
		}
		public PrimaryKeyField SeriesId
		{
			get
			{
				return this.m_SeriesId;
			}
			set
			{
				this.m_SeriesId = value;
			}
		}
		IntField m_StudyId = new IntField("StudyId",null);
		public IntField StudyId
		{
			get
			{
				return this.m_StudyId;
			}
			set
			{
				this.m_StudyId = value;
			}
		}
		TextField m_SeriesInstance = new TextField("SeriesInstance",null);
		public TextField SeriesInstance
		{
			get
			{
				return this.m_SeriesInstance;
			}
			set
			{
				this.m_SeriesInstance = value;
			}
		}
		TextField m_SeriesNumber = new TextField("SeriesNumber",null);
		public TextField SeriesNumber
		{
			get
			{
				return this.m_SeriesNumber;
			}
			set
			{
				this.m_SeriesNumber = value;
			}
		}
		DateTimeField m_SeriesDate = new DateTimeField("SeriesDate",null);
		public DateTimeField SeriesDate
		{
			get
			{
				return this.m_SeriesDate;
			}
			set
			{
				this.m_SeriesDate = value;
			}
		}
		TextField m_Description = new TextField("Description",null);
		public TextField Description
		{
			get
			{
				return this.m_Description;
			}
			set
			{
				this.m_Description = value;
			}
		}
		IntField m_ModalityDetailId = new IntField("ModalityDetailId",null);
		public IntField ModalityDetailId
		{
			get
			{
				return this.m_ModalityDetailId;
			}
			set
			{
				this.m_ModalityDetailId = value;
			}
		}
		TextField m_PatientPosition = new TextField("PatientPosition",null);
		public TextField PatientPosition
		{
			get
			{
				return this.m_PatientPosition;
			}
			set
			{
				this.m_PatientPosition = value;
			}
		}
		TextField m_Contrast = new TextField("Contrast",null);
		public TextField Contrast
		{
			get
			{
				return this.m_Contrast;
			}
			set
			{
				this.m_Contrast = value;
			}
		}
		TextField m_BodyPartExamined = new TextField("BodyPartExamined",null);
		public TextField BodyPartExamined
		{
			get
			{
				return this.m_BodyPartExamined;
			}
			set
			{
				this.m_BodyPartExamined = value;
			}
		}
		TextField m_ProtocolName = new TextField("ProtocolName",null);
		public TextField ProtocolName
		{
			get
			{
				return this.m_ProtocolName;
			}
			set
			{
				this.m_ProtocolName = value;
			}
		}
		TextField m_FrameOfReference = new TextField("FrameOfReference",null);
		public TextField FrameOfReference
		{
			get
			{
				return this.m_FrameOfReference;
			}
			set
			{
				this.m_FrameOfReference = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[11];
			fields[0] = m_StudyId;
			fields[1] = m_SeriesInstance;
			fields[2] = m_SeriesNumber;
			fields[3] = m_SeriesDate;
			fields[4] = m_Description;
			fields[5] = m_ModalityDetailId;
			fields[6] = m_PatientPosition;
			fields[7] = m_Contrast;
			fields[8] = m_BodyPartExamined;
			fields[9] = m_ProtocolName;
			fields[10] = m_FrameOfReference;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[12];
			fields[0] = m_SeriesId;
			fields[1] = m_StudyId;
			fields[2] = m_SeriesInstance;
			fields[3] = m_SeriesNumber;
			fields[4] = m_SeriesDate;
			fields[5] = m_Description;
			fields[6] = m_ModalityDetailId;
			fields[7] = m_PatientPosition;
			fields[8] = m_Contrast;
			fields[9] = m_BodyPartExamined;
			fields[10] = m_ProtocolName;
			fields[11] = m_FrameOfReference;
			return fields;
		}
	}
}
