// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.DICOM
{
	public class DICOMStudyObject : DICOMObject
	{
		override public string GetTableName()
		{
			return "DICOMStudies";
		}
		override public bool HasAccessColumns()
		{
			return false;
		}
		PrimaryKeyField m_StudyInstance = new PrimaryKeyField("StudyInsta",null,false);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_StudyInstance;
		}
		public PrimaryKeyField StudyInstance
		{
			get
			{
				return this.m_StudyInstance;
			}
			set
			{
				this.m_StudyInstance = value;
			}
		}
		TextField m_StudyDate = new TextField("StudyDate",null);
		public TextField StudyDate
		{
			get
			{
				return this.m_StudyDate;
			}
			set
			{
				this.m_StudyDate = value;
			}
		}
		TextField m_StudyTime = new TextField("StudyTime",null);
		public TextField StudyTime
		{
			get
			{
				return this.m_StudyTime;
			}
			set
			{
				this.m_StudyTime = value;
			}
		}
		TextField m_StudyID = new TextField("StudyID",null);
		public TextField StudyID
		{
			get
			{
				return this.m_StudyID;
			}
			set
			{
				this.m_StudyID = value;
			}
		}
		TextField m_AccessionNumber = new TextField("AccessionN",null);
		public TextField AccessionNumber
		{
			get
			{
				return this.m_AccessionNumber;
			}
			set
			{
				this.m_AccessionNumber = value;
			}
		}
		TextField m_ReferringPhysician = new TextField("ReferPhysi",null);
		public TextField ReferringPhysician
		{
			get
			{
				return this.m_ReferringPhysician;
			}
			set
			{
				this.m_ReferringPhysician = value;
			}
		}
		TextField m_PatientsAge = new TextField("PatientsAg",null);
		public TextField PatientsAge
		{
			get
			{
				return this.m_PatientsAge;
			}
			set
			{
				this.m_PatientsAge = value;
			}
		}
		TextField m_PatientsWeight = new TextField("PatientsWe",null);
		public TextField PatientsWeight
		{
			get
			{
				return this.m_PatientsWeight;
			}
			set
			{
				this.m_PatientsWeight = value;
			}
		}
		TextField m_StudyModal = new TextField("StudyModal",null);
		public TextField StudyModal
		{
			get
			{
				return this.m_StudyModal;
			}
			set
			{
				this.m_StudyModal = value;
			}
		}
		TextField m_PatientID = new TextField("PatientID",null);
		public TextField PatientID
		{
			get
			{
				return this.m_PatientID;
			}
			set
			{
				this.m_PatientID = value;
			}
		}
		TextField m_StudyDescription = new TextField("StudyDescr",null);
		public TextField StudyDescription
		{
			get
			{
				return this.m_StudyDescription;
			}
			set
			{
				this.m_StudyDescription = value;
			}
		}
		TextField m_PatientDateOfBirth = new TextField("PatientBir",null);
		public TextField PatientDateOfBirth
		{
			get
			{
				return this.m_PatientDateOfBirth;
			}
			set
			{
				this.m_PatientDateOfBirth = value;
			}
		}
		TextField m_PatientSex = new TextField("PatientSex",null);
		public TextField PatientSex
		{
			get
			{
				return this.m_PatientSex;
			}
			set
			{
				this.m_PatientSex = value;
			}
		}
		TextField m_PatientName = new TextField("PatientNam",null);
		public TextField PatientName
		{
			get
			{
				return this.m_PatientName;
			}
			set
			{
				this.m_PatientName = value;
			}
		}
		DateTimeField m_SyncTime = new DateTimeField("SyncTime",null);
		public DateTimeField SyncTime
		{
			get
			{
				return this.m_SyncTime;
			}
			set
			{
				this.m_SyncTime = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[14];
			fields[0] = m_StudyDate;
			fields[1] = m_StudyTime;
			fields[2] = m_StudyID;
			fields[3] = m_AccessionNumber;
			fields[4] = m_ReferringPhysician;
			fields[5] = m_PatientsAge;
			fields[6] = m_PatientsWeight;
			fields[7] = m_StudyModal;
			fields[8] = m_PatientID;
			fields[9] = m_StudyDescription;
			fields[10] = m_PatientDateOfBirth;
			fields[11] = m_PatientSex;
			fields[12] = m_PatientName;
			fields[13] = m_SyncTime;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[15];
			fields[0] = m_StudyInstance;
			fields[1] = m_StudyDate;
			fields[2] = m_StudyTime;
			fields[3] = m_StudyID;
			fields[4] = m_AccessionNumber;
			fields[5] = m_ReferringPhysician;
			fields[6] = m_PatientsAge;
			fields[7] = m_PatientsWeight;
			fields[8] = m_StudyModal;
			fields[9] = m_PatientID;
			fields[10] = m_StudyDescription;
			fields[11] = m_PatientDateOfBirth;
			fields[12] = m_PatientSex;
			fields[13] = m_PatientName;
			fields[14] = m_SyncTime;
			return fields;
		}
	}
}
