// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class GroupRelationObject : RISObject
	{
		override public string GetTableName()
		{
			return "tGroupRelations";
		}
		override public bool HasAccessColumns()
		{
			return true;
		}
		PrimaryKeyField m_GroupRelationId = new PrimaryKeyField("GroupRelationId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_GroupRelationId;
		}
		public PrimaryKeyField GroupRelationId
		{
			get
			{
				return this.m_GroupRelationId;
			}
			set
			{
				this.m_GroupRelationId = value;
			}
		}
		IntField m_FirstGroupId = new IntField("FirstGroupId",null);
		public IntField FirstGroupId
		{
			get
			{
				return this.m_FirstGroupId;
			}
			set
			{
				this.m_FirstGroupId = value;
			}
		}
		IntField m_SecondGroupId = new IntField("SecondGroupId",null);
		public IntField SecondGroupId
		{
			get
			{
				return this.m_SecondGroupId;
			}
			set
			{
				this.m_SecondGroupId = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[2];
			fields[0] = m_FirstGroupId;
			fields[1] = m_SecondGroupId;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[3];
			fields[0] = m_GroupRelationId;
			fields[1] = m_FirstGroupId;
			fields[2] = m_SecondGroupId;
			return fields;
		}
	}
}
