// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class HospitalObject : RISObject
	{
		override public string GetTableName()
		{
			return "tHospitals";
		}
		override public bool HasAccessColumns()
		{
			return true;
		}
		PrimaryKeyField m_HospitalId = new PrimaryKeyField("HospitalId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_HospitalId;
		}
		public PrimaryKeyField HospitalId
		{
			get
			{
				return this.m_HospitalId;
			}
			set
			{
				this.m_HospitalId = value;
			}
		}
		IntField m_ClientId = new IntField("ClientId",null);
		public IntField ClientId
		{
			get
			{
				return this.m_ClientId;
			}
			set
			{
				this.m_ClientId = value;
			}
		}
		TextField m_Name = new TextField("Name",null);
		public TextField Name
		{
			get
			{
				return this.m_Name;
			}
			set
			{
				this.m_Name = value;
			}
		}
		TextField m_Address = new TextField("Address",null);
		public TextField Address
		{
			get
			{
				return this.m_Address;
			}
			set
			{
				this.m_Address = value;
			}
		}
		TextField m_State = new TextField("State",null);
		public TextField State
		{
			get
			{
				return this.m_State;
			}
			set
			{
				this.m_State = value;
			}
		}
		TextField m_Zip = new TextField("Zip",null);
		public TextField Zip
		{
			get
			{
				return this.m_Zip;
			}
			set
			{
				this.m_Zip = value;
			}
		}
		TextField m_Code = new TextField("Code",null);
		public TextField Code
		{
			get
			{
				return this.m_Code;
			}
			set
			{
				this.m_Code = value;
			}
		}
		TextField m_City = new TextField("City",null);
		public TextField City
		{
			get
			{
				return this.m_City;
			}
			set
			{
				this.m_City = value;
			}
		}
		TextField m_Phone = new TextField("Phone",null);
		public TextField Phone
		{
			get
			{
				return this.m_Phone;
			}
			set
			{
				this.m_Phone = value;
			}
		}
		TextField m_Fax = new TextField("Fax",null);
		public TextField Fax
		{
			get
			{
				return this.m_Fax;
			}
			set
			{
				this.m_Fax = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[9];
			fields[0] = m_ClientId;
			fields[1] = m_Name;
			fields[2] = m_Address;
			fields[3] = m_State;
			fields[4] = m_Zip;
			fields[5] = m_Code;
			fields[6] = m_City;
			fields[7] = m_Phone;
			fields[8] = m_Fax;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[10];
			fields[0] = m_HospitalId;
			fields[1] = m_ClientId;
			fields[2] = m_Name;
			fields[3] = m_Address;
			fields[4] = m_State;
			fields[5] = m_Zip;
			fields[6] = m_Code;
			fields[7] = m_City;
			fields[8] = m_Phone;
			fields[9] = m_Fax;
			return fields;
		}
	}
}
