// Generated by CodeGenerator
// DO NOT MODIFY!
using RIS.RISLibrary.Fields;
using System;
namespace RIS.RISLibrary.Objects.RIS
{
	public class ModalityObject : RISObject
	{
		override public string GetTableName()
		{
			return "tModalities";
		}
		override public bool HasAccessColumns()
		{
			return true;
		}
		PrimaryKeyField m_ModalityId = new PrimaryKeyField("ModalityId",null,true);
		override public PrimaryKeyField GetPrimaryKey()
		{
			return m_ModalityId;
		}
		public PrimaryKeyField ModalityId
		{
			get
			{
				return this.m_ModalityId;
			}
			set
			{
				this.m_ModalityId = value;
			}
		}
		TextField m_Name = new TextField("Name",null);
		public TextField Name
		{
			get
			{
				return this.m_Name;
			}
			set
			{
				this.m_Name = value;
			}
		}
		override public Field[] GetFields()
		{
			Field[] fields = new Field[1];
			fields[0] = m_Name;
			return fields;
		}
		override public Field[] GetAllFields()
		{
			Field[] fields = new Field[2];
			fields[0] = m_ModalityId;
			fields[1] = m_Name;
			return fields;
		}
	}
}
