/**************************************************************************
-- -Generated by xSQL SDK for Data Comparison and Synchronization
-- -Date/Time: May 19, 2010 10:07:23

-- -Summary: Synchronization script that makes the content of the database .\SQL2005.RIS_PROD 
    the same as the content of the database .\SQL2005.RIS.

    BACKUP the database .\SQL2005.RIS_PROD before running this script. 

-- -Action:  Execute this script on .\SQL2005.RIS_PROD

-- -SQL Server version: 9.00.4035
**************************************************************************/

SET XACT_ABORT ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF


BEGIN TRANSACTION

DECLARE @error INT
DECLARE @ptrBinary varbinary(16)

-- -Dropping foreign key: [dbo].[tUsers].[FK_tUsers_tClients]
ALTER TABLE [dbo].[tUsers] DROP CONSTRAINT [FK_tUsers_tClients]

-- -Dropping foreign key: [dbo].[tUsers].[FK_tUsers_tHospitals]
ALTER TABLE [dbo].[tUsers] DROP CONSTRAINT [FK_tUsers_tHospitals]

-- -Dropping foreign key: [dbo].[tFindings].[FK_tFindings_tUsers_Rad]
ALTER TABLE [dbo].[tFindings] DROP CONSTRAINT [FK_tFindings_tUsers_Rad]

-- -Dropping foreign key: [dbo].[tFindings].[FK_tFindings_tUsers_Tran]
ALTER TABLE [dbo].[tFindings] DROP CONSTRAINT [FK_tFindings_tUsers_Tran]

-- -Dropping foreign key: [dbo].[tLog].[FK_tLog_tUsers]
ALTER TABLE [dbo].[tLog] DROP CONSTRAINT [FK_tLog_tUsers]

-- -Dropping foreign key: [dbo].[tStudies].[FK_tStudies_tUsers]
ALTER TABLE [dbo].[tStudies] DROP CONSTRAINT [FK_tStudies_tUsers]

-- -Dropping foreign key: [dbo].[tTemplateUsers].[FK_tTemplateUsers_tUsers]
ALTER TABLE [dbo].[tTemplateUsers] DROP CONSTRAINT [FK_tTemplateUsers_tUsers]

-- -Dropping foreign key: [dbo].[tUserGroups].[FK_tUserGroups_tUsers]
ALTER TABLE [dbo].[tUserGroups] DROP CONSTRAINT [FK_tUserGroups_tUsers]

-- -Dropping foreign key: [dbo].[tUserRoles].[FK_tUserRoles_tUsers]
ALTER TABLE [dbo].[tUserRoles] DROP CONSTRAINT [FK_tUserRoles_tUsers]

-- --Table: [dbo].[tUsers]
-- --Update
SET IDENTITY_INSERT [dbo].[tUsers] ON
UPDATE [dbo].[tUsers] SET [LastLoginDate]='2010-05-13T05:15:34.537', [LastUpdateDate]='2010-05-13T05:15:34.000' WHERE [UserId]=1
UPDATE [dbo].[tUsers] SET [LastLoginDate]='2010-05-19T09:28:41.813', [LastUpdateDate]='2010-05-19T09:28:41.000' WHERE [UserId]=4
UPDATE [dbo].[tUsers] SET [LastLoginDate]='2010-05-19T09:56:19.043', [HospitalId]=4, [LastUpdateDate]='2010-05-19T09:56:19.000' WHERE [UserId]=124
UPDATE [dbo].[tUsers] SET [HospitalId]=23 WHERE [UserId]=206
UPDATE [dbo].[tUsers] SET [HospitalId]=25 WHERE [UserId]=207
UPDATE [dbo].[tUsers] SET [HospitalId]=20 WHERE [UserId]=208
UPDATE [dbo].[tUsers] SET [HospitalId]=9 WHERE [UserId]=209
UPDATE [dbo].[tUsers] SET [HospitalId]=26 WHERE [UserId]=210
UPDATE [dbo].[tUsers] SET [HospitalId]=15 WHERE [UserId]=211
UPDATE [dbo].[tUsers] SET [HospitalId]=26 WHERE [UserId]=212
UPDATE [dbo].[tUsers] SET [HospitalId]=27 WHERE [UserId]=213
UPDATE [dbo].[tUsers] SET [HospitalId]=19 WHERE [UserId]=214
UPDATE [dbo].[tUsers] SET [HospitalId]=15 WHERE [UserId]=215
UPDATE [dbo].[tUsers] SET [HospitalId]=28 WHERE [UserId]=216
UPDATE [dbo].[tUsers] SET [HospitalId]=23 WHERE [UserId]=217
UPDATE [dbo].[tUsers] SET [HospitalId]=8 WHERE [UserId]=218
UPDATE [dbo].[tUsers] SET [HospitalId]=6 WHERE [UserId]=219
UPDATE [dbo].[tUsers] SET [HospitalId]=19 WHERE [UserId]=220
UPDATE [dbo].[tUsers] SET [HospitalId]=27 WHERE [UserId]=221
UPDATE [dbo].[tUsers] SET [HospitalId]=24 WHERE [UserId]=222
UPDATE [dbo].[tUsers] SET [HospitalId]=15 WHERE [UserId]=223
UPDATE [dbo].[tUsers] SET [HospitalId]=28 WHERE [UserId]=224
UPDATE [dbo].[tUsers] SET [HospitalId]=29 WHERE [UserId]=225
UPDATE [dbo].[tUsers] SET [HospitalId]=11 WHERE [UserId]=226
UPDATE [dbo].[tUsers] SET [HospitalId]=30 WHERE [UserId]=227
UPDATE [dbo].[tUsers] SET [HospitalId]=7 WHERE [UserId]=228
UPDATE [dbo].[tUsers] SET [HospitalId]=31 WHERE [UserId]=229
UPDATE [dbo].[tUsers] SET [HospitalId]=21 WHERE [UserId]=230
UPDATE [dbo].[tUsers] SET [HospitalId]=32 WHERE [UserId]=231
UPDATE [dbo].[tUsers] SET [HospitalId]=19 WHERE [UserId]=232
UPDATE [dbo].[tUsers] SET [HospitalId]=33 WHERE [UserId]=233
UPDATE [dbo].[tUsers] SET [HospitalId]=22 WHERE [UserId]=234
UPDATE [dbo].[tUsers] SET [HospitalId]=15 WHERE [UserId]=235
UPDATE [dbo].[tUsers] SET [HospitalId]=34 WHERE [UserId]=236
UPDATE [dbo].[tUsers] SET [HospitalId]=6 WHERE [UserId]=237
UPDATE [dbo].[tUsers] SET [HospitalId]=5 WHERE [UserId]=238
UPDATE [dbo].[tUsers] SET [HospitalId]=18 WHERE [UserId]=239
UPDATE [dbo].[tUsers] SET [HospitalId]=15 WHERE [UserId]=240
UPDATE [dbo].[tUsers] SET [HospitalId]=18 WHERE [UserId]=241
UPDATE [dbo].[tUsers] SET [HospitalId]=23 WHERE [UserId]=242
UPDATE [dbo].[tUsers] SET [HospitalId]=17 WHERE [UserId]=243
UPDATE [dbo].[tUsers] SET [HospitalId]=5 WHERE [UserId]=245
UPDATE [dbo].[tUsers] SET [LastLoginDate]='2010-05-19T09:55:56.777', [LastUpdateDate]='2010-05-19T09:55:56.000' WHERE [UserId]=247

SET IDENTITY_INSERT [dbo].[tUsers] OFF

-- -Creating foreign key: [dbo].[tUsers].[FK_tUsers_tClients]
ALTER TABLE [dbo].[tUsers] WITH NOCHECK ADD 
	CONSTRAINT [FK_tUsers_tClients] FOREIGN KEY 
	(
		[ClientId]
	)REFERENCES [dbo].[tClients](
		[ClientId]
	)ON UPDATE NO ACTION ON DELETE NO ACTION 
ALTER TABLE [dbo].[tUsers] NOCHECK CONSTRAINT [FK_tUsers_tClients]

-- -Creating foreign key: [dbo].[tUsers].[FK_tUsers_tHospitals]
ALTER TABLE [dbo].[tUsers] ADD 
	CONSTRAINT [FK_tUsers_tHospitals] FOREIGN KEY 
	(
		[HospitalId]
	)REFERENCES [dbo].[tHospitals](
		[HospitalId]
	)ON UPDATE NO ACTION ON DELETE NO ACTION 

-- -Creating foreign key: [dbo].[tFindings].[FK_tFindings_tUsers_Rad]
ALTER TABLE [dbo].[tFindings] WITH NOCHECK ADD 
	CONSTRAINT [FK_tFindings_tUsers_Rad] FOREIGN KEY 
	(
		[AudioUserId]
	)REFERENCES [dbo].[tUsers](
		[UserId]
	)ON UPDATE NO ACTION ON DELETE NO ACTION 
ALTER TABLE [dbo].[tFindings] NOCHECK CONSTRAINT [FK_tFindings_tUsers_Rad]

-- -Creating foreign key: [dbo].[tFindings].[FK_tFindings_tUsers_Tran]
ALTER TABLE [dbo].[tFindings] WITH NOCHECK ADD 
	CONSTRAINT [FK_tFindings_tUsers_Tran] FOREIGN KEY 
	(
		[TranscriptUserId]
	)REFERENCES [dbo].[tUsers](
		[UserId]
	)ON UPDATE NO ACTION ON DELETE NO ACTION 
ALTER TABLE [dbo].[tFindings] NOCHECK CONSTRAINT [FK_tFindings_tUsers_Tran]

-- -Creating foreign key: [dbo].[tLog].[FK_tLog_tUsers]
ALTER TABLE [dbo].[tLog] WITH NOCHECK ADD 
	CONSTRAINT [FK_tLog_tUsers] FOREIGN KEY 
	(
		[UserId]
	)REFERENCES [dbo].[tUsers](
		[UserId]
	)ON UPDATE NO ACTION ON DELETE NO ACTION 
ALTER TABLE [dbo].[tLog] NOCHECK CONSTRAINT [FK_tLog_tUsers]

-- -Creating foreign key: [dbo].[tStudies].[FK_tStudies_tUsers]
ALTER TABLE [dbo].[tStudies] ADD 
	CONSTRAINT [FK_tStudies_tUsers] FOREIGN KEY 
	(
		[ReferringPhysicianId]
	)REFERENCES [dbo].[tUsers](
		[UserId]
	)ON UPDATE NO ACTION ON DELETE NO ACTION 

-- -Creating foreign key: [dbo].[tTemplateUsers].[FK_tTemplateUsers_tUsers]
ALTER TABLE [dbo].[tTemplateUsers] WITH NOCHECK ADD 
	CONSTRAINT [FK_tTemplateUsers_tUsers] FOREIGN KEY 
	(
		[UserId]
	)REFERENCES [dbo].[tUsers](
		[UserId]
	)ON UPDATE NO ACTION ON DELETE NO ACTION 
ALTER TABLE [dbo].[tTemplateUsers] NOCHECK CONSTRAINT [FK_tTemplateUsers_tUsers]

-- -Creating foreign key: [dbo].[tUserGroups].[FK_tUserGroups_tUsers]
ALTER TABLE [dbo].[tUserGroups] WITH NOCHECK ADD 
	CONSTRAINT [FK_tUserGroups_tUsers] FOREIGN KEY 
	(
		[UserId]
	)REFERENCES [dbo].[tUsers](
		[UserId]
	)ON UPDATE NO ACTION ON DELETE NO ACTION 
ALTER TABLE [dbo].[tUserGroups] NOCHECK CONSTRAINT [FK_tUserGroups_tUsers]

-- -Creating foreign key: [dbo].[tUserRoles].[FK_tUserRoles_tUsers]
ALTER TABLE [dbo].[tUserRoles] WITH NOCHECK ADD 
	CONSTRAINT [FK_tUserRoles_tUsers] FOREIGN KEY 
	(
		[UserId]
	)REFERENCES [dbo].[tUsers](
		[UserId]
	)ON UPDATE NO ACTION ON DELETE NO ACTION 
ALTER TABLE [dbo].[tUserRoles] NOCHECK CONSTRAINT [FK_tUserRoles_tUsers]


COMMIT TRANSACTION

