/**************************************************************************
-- -Generated by xSQL SDK for Data Comparison and Synchronization
-- -Date/Time: July 2, 2010 00:40:54

-- -Summary: Synchronization script that makes the content of the database .\SQL2005.RIS_PROD 
    the same as the content of the database .\SQL2005.RIS.

    BACKUP the database .\SQL2005.RIS_PROD before running this script. 

-- -Action:  Execute this script on .\SQL2005.RIS_PROD

-- -SQL Server version: 9.00.4053
**************************************************************************/

SET XACT_ABORT ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF


BEGIN TRANSACTION

DECLARE @error INT
DECLARE @ptrBinary varbinary(16)

-- --Table: [dbo].[tClients]
-- --Update
SET IDENTITY_INSERT [dbo].[tClients] ON
UPDATE [dbo].[tClients] SET [Address]='127 Mandon Lane', [City]='Jackson', [State]='MS', [Zip]='39208', [CreatedBy]=1, [CreationDate]='2001-01-01T00:00:00.000', [LastUpdatedBy]=1, [LastUpdateDate]='2001-01-01T00:00:00.000' WHERE [ClientId]=1

-- --Insert
INSERT INTO [dbo].[tClients] ([ClientId], [ClientGUID], [Name], [Address], [City], [State], [Zip], [Phone], [Fax], [CreatedBy], [CreationDate], [LastUpdatedBy], [LastUpdateDate]) VALUES(2, null, 'Scott Medical Imaging', '730 Ridgewood Road Suite C', 'Ridgeland', 'MS', '39157', '(601) 957-6447', '(601) 206-5606', 1, '2001-01-01T00:00:00.000', 1, '2001-01-01T00:00:00.000')
INSERT INTO [dbo].[tClients] ([ClientId], [ClientGUID], [Name], [Address], [City], [State], [Zip], [Phone], [Fax], [CreatedBy], [CreationDate], [LastUpdatedBy], [LastUpdateDate]) VALUES(3, null, 'Ridgeland Diagnostic Center', '730 Ridgewood Road Suite C', 'Ridgeland', 'MS', '39157', '(601) 206-5605', '(601) 206-5606', 1, '2001-01-01T00:00:00.000', 1, '2001-01-01T00:00:00.000')

SET IDENTITY_INSERT [dbo].[tClients] OFF


COMMIT TRANSACTION

